/** 
# Calculator-App
This my second Git project on the calculator

 

/**
 *
 * @author 2004g
 */
public class SimpleCalculator extends javax.swing.JFrame {
    double num1 = 0, num2=0;
    String operator = null;
//Han ye bhi likh sakte hai 
    //double first;
    //double second ;
    //double result;
    //String opration;
    //String answer;
    private Object display;
    
    public SimpleCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton19 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        B11 = new javax.swing.JButton();
        B12 = new javax.swing.JButton();
        B13 = new javax.swing.JButton();
        B14 = new javax.swing.JButton();
        B16 = new javax.swing.JButton();
        B15 = new javax.swing.JButton();
        B17 = new javax.swing.JButton();
        B18 = new javax.swing.JButton();
        B19 = new javax.swing.JButton();
        BCosec = new javax.swing.JButton();
        BDiv1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        B4 = new javax.swing.JButton();
        BDiv = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        BMul = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        BSub = new javax.swing.JButton();
        B0 = new javax.swing.JButton();
        BDot = new javax.swing.JButton();
        BEqual = new javax.swing.JButton();
        BAdd = new javax.swing.JButton();
        BClear = new javax.swing.JButton();
        BBack = new javax.swing.JButton();
        BRoot = new javax.swing.JButton();
        BPercent = new javax.swing.JButton();
        BReciprocal = new javax.swing.JButton();
        BPI = new javax.swing.JButton();
        BPlusMinus = new javax.swing.JButton();
        BFactorial = new javax.swing.JButton();
        BCube = new javax.swing.JButton();
        BXPowerY = new javax.swing.JButton();
        BSin = new javax.swing.JButton();
        BCos = new javax.swing.JButton();
        BTan = new javax.swing.JButton();
        BSinh = new javax.swing.JButton();
        BCosh = new javax.swing.JButton();
        BLog = new javax.swing.JButton();
        BExp = new javax.swing.JButton();
        BTanh = new javax.swing.JButton();
        BCosecx = new javax.swing.JButton();
        BSec = new javax.swing.JButton();
        BCot = new javax.swing.JButton();
        BOF = new javax.swing.JRadioButton();
        BOn = new javax.swing.JRadioButton();
        BCosecInverse = new javax.swing.JButton();
        BX = new javax.swing.JButton();
        BCap = new javax.swing.JButton();
        BCosInverse = new javax.swing.JButton();
        BTanInverse = new javax.swing.JButton();
        BCotInverse = new javax.swing.JButton();
        BSecInverse = new javax.swing.JButton();
        BSinInverse = new javax.swing.JButton();
        BCloseBracket = new javax.swing.JButton();
        BZ = new javax.swing.JButton();
        BOpenBracket = new javax.swing.JButton();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jProgressBar5 = new javax.swing.JProgressBar();
        jProgressBar6 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        jButton19.setText("7");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton17.setText("7");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("7");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton20.setText("7");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        B10.setText("0");
        B10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B10ActionPerformed(evt);
            }
        });

        B11.setText("0");
        B11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B11ActionPerformed(evt);
            }
        });

        B12.setText("0");
        B12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B12ActionPerformed(evt);
            }
        });

        B13.setText("0");
        B13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B13ActionPerformed(evt);
            }
        });

        B14.setText("0");
        B14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B14ActionPerformed(evt);
            }
        });

        B16.setText("0");
        B16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B16ActionPerformed(evt);
            }
        });

        B15.setText("0");
        B15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B15ActionPerformed(evt);
            }
        });

        B17.setText("0");
        B17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B17ActionPerformed(evt);
            }
        });

        B18.setText("0");
        B18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B18ActionPerformed(evt);
            }
        });

        B19.setText("0");
        B19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B19ActionPerformed(evt);
            }
        });

        BCosec.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        BCosec.setText("Cosec");
        BCosec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCosecActionPerformed(evt);
            }
        });

        BDiv1.setText("Cose");
        BDiv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDiv1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(60, 11, 98));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 8)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Matrix");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculator");

        T1.setBackground(new java.awt.Color(0, 51, 51));
        T1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        T1.setForeground(new java.awt.Color(0, 102, 102));
        T1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        T1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));
        T1.setCaretColor(new java.awt.Color(0, 51, 51));
        T1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });

        B4.setBackground(new java.awt.Color(204, 204, 204));
        B4.setForeground(new java.awt.Color(0, 0, 0));
        B4.setText("4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        BDiv.setBackground(new java.awt.Color(204, 102, 0));
        BDiv.setText("/");
        BDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDivActionPerformed(evt);
            }
        });

        B8.setBackground(new java.awt.Color(204, 204, 204));
        B8.setForeground(new java.awt.Color(0, 0, 0));
        B8.setText("8");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B9.setBackground(new java.awt.Color(204, 204, 204));
        B9.setForeground(new java.awt.Color(0, 0, 0));
        B9.setText("9");
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        B5.setBackground(new java.awt.Color(204, 204, 204));
        B5.setForeground(new java.awt.Color(0, 0, 0));
        B5.setText("5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setBackground(new java.awt.Color(204, 204, 204));
        B6.setForeground(new java.awt.Color(0, 0, 0));
        B6.setText("6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B7.setBackground(new java.awt.Color(204, 204, 204));
        B7.setForeground(new java.awt.Color(0, 0, 0));
        B7.setText("7");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        BMul.setBackground(new java.awt.Color(204, 102, 0));
        BMul.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        BMul.setText("*");
        BMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMulActionPerformed(evt);
            }
        });

        B1.setBackground(new java.awt.Color(204, 204, 204));
        B1.setForeground(new java.awt.Color(0, 0, 0));
        B1.setText("1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setBackground(new java.awt.Color(204, 204, 204));
        B2.setForeground(new java.awt.Color(0, 0, 0));
        B2.setText("2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setBackground(new java.awt.Color(204, 204, 204));
        B3.setForeground(new java.awt.Color(0, 0, 0));
        B3.setText("3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        BSub.setBackground(new java.awt.Color(204, 102, 0));
        BSub.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        BSub.setText("-");
        BSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSubActionPerformed(evt);
            }
        });

        B0.setBackground(new java.awt.Color(204, 204, 204));
        B0.setForeground(new java.awt.Color(0, 0, 0));
        B0.setText("0");
        B0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0ActionPerformed(evt);
            }
        });

        BDot.setBackground(new java.awt.Color(204, 102, 0));
        BDot.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BDot.setText(".");
        BDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDotActionPerformed(evt);
            }
        });

        BEqual.setBackground(new java.awt.Color(0, 0, 0));
        BEqual.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BEqual.setForeground(new java.awt.Color(255, 255, 255));
        BEqual.setText("=");
        BEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEqualActionPerformed(evt);
            }
        });

        BAdd.setBackground(new java.awt.Color(204, 102, 0));
        BAdd.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        BAdd.setText("+");
        BAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddActionPerformed(evt);
            }
        });

        BClear.setBackground(new java.awt.Color(204, 0, 0));
        BClear.setFont(new java.awt.Font("Segoe UI Emoji", 2, 24)); // NOI18N
        BClear.setForeground(new java.awt.Color(255, 255, 255));
        BClear.setText("Clear");
        BClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BClearActionPerformed(evt);
            }
        });

        BBack.setBackground(new java.awt.Color(255, 255, 255));
        BBack.setFont(new java.awt.Font("Segoe UI Variable", 3, 18)); // NOI18N
        BBack.setForeground(new java.awt.Color(0, 0, 0));
        BBack.setText("Back");
        BBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBackActionPerformed(evt);
            }
        });

        BRoot.setBackground(new java.awt.Color(204, 102, 0));
        BRoot.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        BRoot.setText("√");
        BRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRootActionPerformed(evt);
            }
        });

        BPercent.setBackground(new java.awt.Color(204, 102, 0));
        BPercent.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BPercent.setText("%");
        BPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPercentActionPerformed(evt);
            }
        });

        BReciprocal.setBackground(new java.awt.Color(153, 102, 255));
        BReciprocal.setForeground(new java.awt.Color(255, 255, 255));
        BReciprocal.setText("1/x");
        BReciprocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReciprocalActionPerformed(evt);
            }
        });

        BPI.setBackground(new java.awt.Color(153, 102, 255));
        BPI.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BPI.setForeground(new java.awt.Color(255, 255, 255));
        BPI.setText("π");
        BPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPIActionPerformed(evt);
            }
        });

        BPlusMinus.setBackground(new java.awt.Color(204, 102, 0));
        BPlusMinus.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        BPlusMinus.setText("+/-");
        BPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPlusMinusActionPerformed(evt);
            }
        });

        BFactorial.setBackground(new java.awt.Color(153, 102, 255));
        BFactorial.setForeground(new java.awt.Color(255, 255, 255));
        BFactorial.setText("n!");
        BFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFactorialActionPerformed(evt);
            }
        });

        BCube.setBackground(new java.awt.Color(153, 102, 255));
        BCube.setForeground(new java.awt.Color(255, 255, 255));
        BCube.setText("X^3");
        BCube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCubeActionPerformed(evt);
            }
        });

        BXPowerY.setBackground(new java.awt.Color(153, 102, 255));
        BXPowerY.setForeground(new java.awt.Color(255, 255, 255));
        BXPowerY.setText("X^Y");
        BXPowerY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BXPowerYActionPerformed(evt);
            }
        });

        BSin.setBackground(new java.awt.Color(51, 204, 255));
        BSin.setForeground(new java.awt.Color(0, 0, 0));
        BSin.setText("Sin");
        BSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSinActionPerformed(evt);
            }
        });

        BCos.setBackground(new java.awt.Color(51, 204, 255));
        BCos.setForeground(new java.awt.Color(0, 0, 0));
        BCos.setText("Cos");
        BCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCosActionPerformed(evt);
            }
        });

        BTan.setBackground(new java.awt.Color(51, 204, 255));
        BTan.setForeground(new java.awt.Color(0, 0, 0));
        BTan.setText("Tan");
        BTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTanActionPerformed(evt);
            }
        });

        BSinh.setBackground(new java.awt.Color(102, 204, 255));
        BSinh.setForeground(new java.awt.Color(0, 0, 0));
        BSinh.setText("Sinh");
        BSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSinhActionPerformed(evt);
            }
        });

        BCosh.setBackground(new java.awt.Color(102, 204, 255));
        BCosh.setForeground(new java.awt.Color(0, 0, 0));
        BCosh.setText("Cosh");
        BCosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCoshActionPerformed(evt);
            }
        });

        BLog.setBackground(new java.awt.Color(51, 204, 255));
        BLog.setForeground(new java.awt.Color(0, 0, 0));
        BLog.setText("Log");
        BLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLogActionPerformed(evt);
            }
        });

        BExp.setBackground(new java.awt.Color(51, 204, 255));
        BExp.setForeground(new java.awt.Color(0, 0, 0));
        BExp.setText("e^x");
        BExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExpActionPerformed(evt);
            }
        });

        BTanh.setBackground(new java.awt.Color(102, 204, 255));
        BTanh.setForeground(new java.awt.Color(0, 0, 0));
        BTanh.setText("Tanh");
        BTanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTanhActionPerformed(evt);
            }
        });

        BCosecx.setBackground(new java.awt.Color(102, 204, 255));
        BCosecx.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        BCosecx.setForeground(new java.awt.Color(0, 0, 0));
        BCosecx.setText("Cosecx");
        BCosecx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCosecxActionPerformed(evt);
            }
        });

        BSec.setBackground(new java.awt.Color(102, 204, 255));
        BSec.setForeground(new java.awt.Color(0, 0, 0));
        BSec.setText("Sec");
        BSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSecActionPerformed(evt);
            }
        });

        BCot.setBackground(new java.awt.Color(102, 204, 255));
        BCot.setForeground(new java.awt.Color(0, 0, 0));
        BCot.setText("Cot");
        BCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCotActionPerformed(evt);
            }
        });

        BOF.setBackground(new java.awt.Color(255, 0, 0));
        BOF.setForeground(new java.awt.Color(0, 0, 0));
        BOF.setText("OF");
        BOF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 51, 153)));
        BOF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOFActionPerformed(evt);
            }
        });

        BOn.setBackground(new java.awt.Color(0, 102, 0));
        BOn.setForeground(new java.awt.Color(0, 0, 153));
        BOn.setText("ON");
        BOn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        BOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOnActionPerformed(evt);
            }
        });

        BCosecInverse.setBackground(new java.awt.Color(153, 102, 255));
        BCosecInverse.setForeground(new java.awt.Color(255, 255, 255));
        BCosecInverse.setText("Cosec^-1");
        BCosecInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCosecInverseActionPerformed(evt);
            }
        });

        BX.setBackground(new java.awt.Color(255, 102, 51));
        BX.setText("X");
        BX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BXActionPerformed(evt);
            }
        });

        BCap.setBackground(new java.awt.Color(255, 102, 0));
        BCap.setFont(new java.awt.Font("Segoe UI Historic", 3, 10)); // NOI18N
        BCap.setText("^");
        BCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCapActionPerformed(evt);
            }
        });

        BCosInverse.setBackground(new java.awt.Color(153, 102, 255));
        BCosInverse.setForeground(new java.awt.Color(255, 255, 255));
        BCosInverse.setText("Cos^-1");
        BCosInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCosInverseActionPerformed(evt);
            }
        });

        BTanInverse.setBackground(new java.awt.Color(153, 102, 255));
        BTanInverse.setForeground(new java.awt.Color(255, 255, 255));
        BTanInverse.setText("Tan^-1");
        BTanInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTanInverseActionPerformed(evt);
            }
        });

        BCotInverse.setBackground(new java.awt.Color(153, 102, 255));
        BCotInverse.setForeground(new java.awt.Color(255, 255, 255));
        BCotInverse.setText("Cot^-1");
        BCotInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCotInverseActionPerformed(evt);
            }
        });

        BSecInverse.setBackground(new java.awt.Color(153, 102, 255));
        BSecInverse.setForeground(new java.awt.Color(255, 255, 255));
        BSecInverse.setText("BSec^-1");
        BSecInverse.setActionCommand("BCosec^-1");
        BSecInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSecInverseActionPerformed(evt);
            }
        });

        BSinInverse.setBackground(new java.awt.Color(102, 204, 255));
        BSinInverse.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        BSinInverse.setForeground(new java.awt.Color(0, 0, 0));
        BSinInverse.setText("Sin^-1");
        BSinInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSinInverseActionPerformed(evt);
            }
        });

        BCloseBracket.setBackground(new java.awt.Color(204, 102, 0));
        BCloseBracket.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BCloseBracket.setText(")");
        BCloseBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCloseBracketActionPerformed(evt);
            }
        });

        BZ.setBackground(new java.awt.Color(255, 102, 0));
        BZ.setText("Z");
        BZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BZActionPerformed(evt);
            }
        });

        BOpenBracket.setBackground(new java.awt.Color(204, 102, 0));
        BOpenBracket.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BOpenBracket.setText("(   ");
        BOpenBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOpenBracketActionPerformed(evt);
            }
        });

        jProgressBar4.setBackground(new java.awt.Color(0, 102, 102));
        jProgressBar4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 165, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(883, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(627, 627, 627)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(BOF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(BOn)
                                        .addGap(139, 139, 139)
                                        .addComponent(BEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BSin, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BCosecx, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BDot, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BCos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BSec, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(BCube, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BOpenBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BCloseBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BTan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BCot, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(BPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                                .addComponent(BSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BMul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(BXPowerY)
                                            .addComponent(BLog)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(BSinInverse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BExp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(BCosecInverse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                            .addComponent(BCotInverse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BTanInverse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BSecInverse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BReciprocal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BZ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BCap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BCosInverse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(BBack, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BClear, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))))
                    .addComponent(jProgressBar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(607, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jProgressBar6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BOF)
                            .addComponent(BOn)
                            .addComponent(BEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BCloseBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BOpenBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BCube, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(BTan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BCot, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BDot, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(BCos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BSec, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BMul, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BSub, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BPI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BXPowerY, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BLog, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BCotInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BExp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BSinInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BCosInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(BRoot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(BSin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BCosecx, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BCap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(BX, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BZ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BReciprocal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BSecInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTanInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BCosecInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(936, 936, 936))
        );

        pack();
    }// </editor-fold>                        

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        T1.setText(T1.getText() + "4");
    }                                  

    private void BDivActionPerformed(java.awt.event.ActionEvent evt) {                                     
      num1 = Double.parseDouble(T1.getText());
      T1.setText("");
      operator = "/";
      //Second Logic
    //else if(operation=="/"){
     //result = first+second;
            //answer = String.format("%.2f",result);
       //}  
      
    }                                    

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        T1.setText(T1.getText() + "8");
    }                                  

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        T1.setText(T1.getText() + "9");
    }                                  

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        T1.setText(T1.getText() + "5");
    }                                  

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        T1.setText(T1.getText() + "6");
        
    }                                  

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        T1.setText(T1.getText() + "7");
    }                                  

    private void BMulActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        num1 = Double.parseDouble(T1.getText());
        T1.setText("");
        operator= "*";
      
    }                                    

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        T1.setText(T1.getText() + "1");
                
    }                                  

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        T1.setText(T1.getText() + "2");
    }                                  

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        T1.setText(T1.getText() + "3");
    }                                  

    private void BSubActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        num1 = Double.parseDouble(T1.getText());
        T1.setText("");
        operator = "-";
    }                                    

    private void B0ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        T1.setText(T1.getText() + "0");
    }                                  

    private void BDotActionPerformed(java.awt.event.ActionEvent evt) {                                     
        
        T1.setText(T1.getText() + ".");
    }                                    

    private void BEqualActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        num2 = Double.parseDouble(T1.getText());
        //Second = Double.parseDouble(T1.getText());
        double ans =0;
        
        if (T1.getText().equals("") || T1.getText() == null) {
            T1.setText("Error: Input Required");
            operator = null;
               return;
        }

        double num2 = Double.parseDouble(T1.getText());


        
        if(operator=="+"){
        //if(operation=="+') {
            //result = first+second;
            //answer = String.format("%.2f",result);
       //}     
            
            ans = num1 + num2;
        }
        
  
         else if(operator=="-"){
            ans = num1-num2;
        }
          else if(operator=="+"){
            ans = num1+num2;
        }
        
          else if(operator=="/"){
            
            ans =  num1/num2;
        }
        
        
          else if(operator=="*"){           
            ans = num1*num2;
        }
        
        num2 = Double.parseDouble(T1.getText()); // doosra number
    
        if(operator.equals("%")) {
           ans = (num1 * num2) / 100; // percentage calculation
        }
        
      
        
        else if(operator== "X^Y"){
            
            double answer = Math.pow(num1, num2);
            T1.setText(String.valueOf(answer));
            
    //for all trignometru function        
        }
         else if(operator=="Sin"){
           ans = Math.sin(Math.toRadians(num1));
        
        }
        
        else if (operator.equals("cos")) {
            ans = Math.cos(Math.toRadians(num1));
        }
        else if (operator.equals("tan")) {
             ans = Math.tan(Math.toRadians(num1));
        }
        
        //for inverse ke liye
         else if (operator.equals("asin")) {
             ans = Math.toDegrees(Math.asin(num1));
         } 
         else if (operator.equals("acos")) {
              ans = Math.toDegrees(Math.acos(num1));
         } 
         else if (operator.equals("atan")) {
              ans = Math.toDegrees(Math.atan(num1));
          } 
        else if (operator.equals("acosec")) {
           ans = Math.toDegrees(Math.asin(1 / num1));
        } 
        else if (operator.equals("asec")) {
            ans = Math.toDegrees(Math.acos(1 / num1));
        } 
        else if (operator.equals("acot")) {
             ans = Math.toDegrees(Math.atan(1 / num1));
        }

        else if (operator.equals("^")) {
           ans = Math.pow(num1, num2);   // 👈 power ke liye
         }
        
       
         T1.setText(String.valueOf(ans));
         
        
//for ansewr ke liye in button
        T1.setText("" + ans);
        
         operator = null;
    }                                      

    private void BAddActionPerformed(java.awt.event.ActionEvent evt) {                                     
        
        num1 = Double.parseDouble(T1.getText());
        T1.setText("");
        operator = "+";
   //first= Double.parseDouble(T1.getText);
   //T1.setText("");
   //operation="+";
      
    }                                    

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
    }                                         

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void BClearActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        T1.setText(null);
        
    }                                      

    private void BBackActionPerformed(java.awt.event.ActionEvent evt) {                                      
       String str = T1.getText();
       T1.setText(str.substring(0,str.length()-1));
       //2//Second Logic
       //String back=null;
       
       //if(T1.getText().lenght()>0){
         //StringBuilder str = new StringBuilder(T1.getText()):
         //str.deleteCharAt(T1.getText().length()-1);
         //backSpace = str.toString();
         //T1.setText(backSpace);
      //}
       
    }                                     

    private void B10ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void B11ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void B12ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void B13ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void B14ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void B15ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void B16ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void B17ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void B18ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void B19ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void BRootActionPerformed(java.awt.event.ActionEvent evt) {                                      
        
        double a = Math.sqrt(Double.parseDouble(T1.getText()));
        T1.setText("");
        T1.setText(T1.getText()+ a);
        
    }                                     

    private void BPercentActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        double a = Double.parseDouble(T1.getText());
        a = a/100;
        T1.setText(String.valueOf(a));
    }                                        

    private void BReciprocalActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // 1/x , x ka reciprocal
        double a = 1/(Double.parseDouble(T1.getText()));
        T1.setText("");
        T1.setText(T1.getText()+ a);
    }                                           

    private void BPIActionPerformed(java.awt.event.ActionEvent evt) {                                    
      
       
        num1=Math.PI;
       
        T1.setText(String.valueOf(Math.PI));
         operator = "PI";
    }                                   

    private void BPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        double a;
        a = Double.parseDouble(String.valueOf(T1.getText()));
        a=a*(-1);
        T1.setText(String.valueOf(a));
        
    }                                          

    private void BFactorialActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
       double a = Double.parseDouble(T1.getText());
       double fact = 1;
       while(a!=0){
           fact=fact*a;
           a--;
       }
       T1.setText("");
       T1.setText(T1.getText()+fact);
       
    }                                          

    private void BCubeActionPerformed(java.awt.event.ActionEvent evt) {                                      
       //For cube ke liye
        double a;
        a = Double.parseDouble(String.valueOf(T1.getText()));
        a=a*a*a;
        T1.setText("");
        T1.setText(String.valueOf(a));
        operator="X^3";
    }                                     

    private void BXPowerYActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        num1 = Double.parseDouble(T1.getText());
        T1.setText("");
        operator = "PI";
        
    }                                        

    private void BSinActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        double x = Double.parseDouble(T1.getText());
        double a = Math.sin(Math.toRadians(x));
        T1.setText("");
        T1.setText(T1.getText()+ a);
      //2//Second Logic 
      //double a = Math.sin(Double.parseDouble(T1.getText()));
      //T1.setText(""0;
      //T1.setText(T1.getText() + a);
    }                                    

    private void BCosActionPerformed(java.awt.event.ActionEvent evt) {                                     
       
        double x = Double.parseDouble(T1.getText());
        double a = Math.cos(Math.toRadians(x));
        T1.setText("");
        T1.setText(T1.getText()+ a);
    }                                    

    private void BCosecActionPerformed(java.awt.event.ActionEvent evt) {                                       
        double x = Double.parseDouble(T1.getText());
        double y = Math.toRadians(x);
        double a = 1/Math.toRadians(y);
        T1.setText("" + a);
    }                                      

    private void BTanActionPerformed(java.awt.event.ActionEvent evt) {                                     
        double x = Double.parseDouble(T1.getText());
        double a = Math.tan(Math.toRadians(x));
        T1.setText("");
        T1.setText(T1.getText()+ a);
        operator="Tan-1";
    }                                    

    private void BSinhActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        double a = Math.sinh(Double.parseDouble(T1.getText()));
        T1.setText("");
        T1.setText(T1.getText()+ a);
    }                                     

    private void BCoshActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        double a = Math.cosh(Double.parseDouble(T1.getText()));
        T1.setText("");
        T1.setText(T1.getText()+ a);
    }                                     

    private void BLogActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        double a = Math.log(Double.parseDouble(T1.getText()));
        T1.setText("");
        T1.setText(T1.getText() + a);
        
    }                                    

    private void BExpActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        num1 = Double.parseDouble(T1.getText());
        T1.setText("");
        
        operator = "e^x";
        
    }                                    

    private void BTanhActionPerformed(java.awt.event.ActionEvent evt) {                                      
       
        double a = Math.tanh(Double.parseDouble(T1.getText()));
        T1.setText("");
        T1.setText(T1.getText()+ a);
    }                                     

    private void BCosecxActionPerformed(java.awt.event.ActionEvent evt) {                                        
       
        double a = Double.parseDouble(T1.getText());
        double radians = Math.toRadians(a);//degree to radian conversion
        double b = 1/Math.sin(radians);
        T1.setText("");
        T1.setText(T1.getText()+ b);
        operator="Cosecx";
    }                                       

    private void BSecActionPerformed(java.awt.event.ActionEvent evt) {                                     
     
        double a = Double.parseDouble(T1.getText());
        double radians = Math.toRadians(a);
        double b = 1/Math.cos(radians);
        T1.setText("");
        T1.setText(T1.getText()+ b);
    }                                    

    private void BCotActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        
        double a = Double.parseDouble(T1.getText());
        double radians = Math.toRadians(a);
        double b = 1/Math.tan(radians);
        T1.setText("");
        T1.setText(T1.getText()+ b);
    }                                    

    private void BOnActionPerformed(java.awt.event.ActionEvent evt) {                                    
       
        T1.setEnabled(true);   // result screen enable
    
    // buttons enable
    BAdd.setEnabled(true);
    BSub.setEnabled(true);
    BMul.setEnabled(true);
    BDiv.setEnabled(true);
    BEqual.setEnabled(true);
    BDot.setEnabled(true);
    BBack.setEnabled(true);
    BClear.setEnabled(true);

    // Advanced Functions
    BRoot.setEnabled(true);
    BPercent.setEnabled(true);
    BX.setEnabled(true);
    BPI.setEnabled(true);
    BXPowerY.setEnabled(true);
    BCube.setEnabled(true);
    BCap.setEnabled(true);
    BZ.setEnabled(true);
    BFactorial.setEnabled(true);
    BPlusMinus.setEnabled(true);

    // Trigonometric
    BSin.setEnabled(true);
    BCos.setEnabled(true);
    BTan.setEnabled(true);
    BSinh.setEnabled(true);
    BCosh.setEnabled(true);
    BTanh.setEnabled(true);
    BLog.setEnabled(true);
    BExp.setEnabled(true);// e ki ghat x ho expontential
    BReciprocal.setEnabled(true);
    BSinInverse.setEnabled(true);
    BCosInverse.setEnabled(true);
    BTanInverse.setEnabled(true);
    BSecInverse.setEnabled(true);
    BCosecx.setEnabled(true);


    // Extra (sec, cosec, cot)
    BSec.setEnabled(true);
    BCosec.setEnabled(true);
    BCosecInverse.setEnabled(true);
    BCot.setEnabled(true);
    BCotInverse.setEnabled(true);
    
        //number
    B1.setEnabled(true);
    B2.setEnabled(true);
    B3.setEnabled(true);
    B4.setEnabled(true);
    B5.setEnabled(true);
    B6.setEnabled(true);
    B7.setEnabled(true);
    B8.setEnabled(true);
    B9.setEnabled(true);
    B0.setEnabled(true);
    BMul.setEnabled(true);
    BDiv.setEnabled(true);
    BEqual.setEnabled(true);
    BDot.setEnabled(true);
    BBack.setEnabled(true);
    BClear.setEnabled(true);
    BCloseBracket.setEnabled(true);
    BOpenBracket.setEnabled(true);
     
    }                                   

    private void BOFActionPerformed(java.awt.event.ActionEvent evt) {                                    
    T1.setEnabled(false);
    operator = "OF";
         // buttons enable
    BAdd.setEnabled(false);
    BSub.setEnabled(false);
    BMul.setEnabled(false);
    BDiv.setEnabled(false);
    BEqual.setEnabled(false);
    BDot.setEnabled(false);
    BBack.setEnabled(false);
    BClear.setEnabled(false);

    // Advanced Functions
    BRoot.setEnabled(false);
    BPercent.setEnabled(false);
    BX.setEnabled(false);
    BPI.setEnabled(false);
    BXPowerY.setEnabled(false);
    BCube.setEnabled(false);
    BCap.setEnabled(false);
    BFactorial.setEnabled(false);
    BPlusMinus.setEnabled(false);

    // Trigonometric
    BSin.setEnabled(false);
    BCos.setEnabled(false);
    BTan.setEnabled(false);
    BSinh.setEnabled(false);
    BCosh.setEnabled(false);
    BTanh.setEnabled(false);
    BLog.setEnabled(false);
    BExp.setEnabled(false);// e ki ghat x ho expontential
    BReciprocal.setEnabled(false);
    BSinInverse.setEnabled(false);
    BCosInverse.setEnabled(false);
    BTanInverse.setEnabled(false);
    

    // Extra (sec, cosec, cot)
    BSec.setEnabled(false);
    BCosecx.setEnabled(false);
    BCot.setEnabled(false);
    BSecInverse.setEnabled(false);
    BCotInverse.setEnabled(false);
    BCosecInverse.setEnabled(false);
    
    //number
    B1.setEnabled(false);
    B2.setEnabled(false);
    B3.setEnabled(false);
    B4.setEnabled(false);
    B5.setEnabled(false);
    B6.setEnabled(false);
    B7.setEnabled(false);
    B8.setEnabled(false);
    B9.setEnabled(false);
    B0.setEnabled(false);
    BMul.setEnabled(false);
    BDiv.setEnabled(false);
    BEqual.setEnabled(false);
    BDot.setEnabled(false);
    BBack.setEnabled(false);
    BClear.setEnabled(false);
    
    //Degree Related
    BZ.setEnabled(false);
    BCloseBracket.setEnabled(false);
    BOpenBracket.setEnabled(false);
        
     
    }                                   

    private void BDiv1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
         num1 = Double.parseDouble(T1.getText());
        T1.setText("");
        operator= "X";
    }                                     

    private void BCosecInverseActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        double x = Double.parseDouble(T1.getText());
        double a = Math.toDegrees(Math.asin(1/x));
        T1.setText("");
        T1.setText(" " + a);
        operator = "tan^-1";
        
    }                                             

    private void BXActionPerformed(java.awt.event.ActionEvent evt) {                                   
       
//        num1 = Double.parseDouble(T1.getText());
//        T1.setText("");
//        operator= "X";
//      

    }                                  

    private void BCapActionPerformed(java.awt.event.ActionEvent evt) {                                     
        
        num1 = Double.parseDouble(T1.getText());  // pehla number store karo
        operator = "^";                           // operator store karo
        T1.setText("");                           // screen clear karo
                        
                                        
       
     
    }                                    

    private void BCosInverseActionPerformed(java.awt.event.ActionEvent evt) {                                            
        double x = Double.parseDouble(T1.getText());
        double a = Math.toDegrees(Math.acos(x));
        T1.setText(" " + a);
        operator = "Cos^-1";
    }                                           

    private void BTanInverseActionPerformed(java.awt.event.ActionEvent evt) {                                            
        double x = Double.parseDouble(T1.getText());
        double a = Math.toDegrees(Math.atan(x));
        T1.setText(" " + a);
        operator = "tan^-1";
        
    }                                           

    private void BCotInverseActionPerformed(java.awt.event.ActionEvent evt) {                                            
        
        double x = Double.parseDouble(T1.getText());
        double a = Math.toDegrees(Math.atan(1/x));
        T1.setText("");
        T1.setText(" " + a);
        operator = "Cot^-1";
    }                                           

    private void BSecInverseActionPerformed(java.awt.event.ActionEvent evt) {                                            
         //Java me directly asec, acosec, acot nahi hote
        double x = Double.parseDouble(T1.getText());
        double a = Math.toDegrees(Math.acos(1/x));
        T1.setText(" " + a);
        operator = "sec^-1";
    }                                           

    private void BSinInverseActionPerformed(java.awt.event.ActionEvent evt) {                                            
       
        double x = Double.parseDouble(T1.getText());
        double a = Math.toDegrees(Math.asin(x));
        T1.setText(" " + a);
        operator = "Sin^-1";
    }                                           

    private void BCloseBracketActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        T1.setText(T1.getText() + "(");
        operator = "(";
    }                                             

    private void BZActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
       
    }                                  

    private void BOpenBracketActionPerformed(java.awt.event.ActionEvent evt) {                                             
        T1.setText(T1.getText() + ")");
        operator = ")";
    }                                            

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton B0;
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B11;
    private javax.swing.JButton B12;
    private javax.swing.JButton B13;
    private javax.swing.JButton B14;
    private javax.swing.JButton B15;
    private javax.swing.JButton B16;
    private javax.swing.JButton B17;
    private javax.swing.JButton B18;
    private javax.swing.JButton B19;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton BAdd;
    private javax.swing.JButton BBack;
    private javax.swing.JButton BCap;
    private javax.swing.JButton BClear;
    private javax.swing.JButton BCloseBracket;
    private javax.swing.JButton BCos;
    private javax.swing.JButton BCosInverse;
    private javax.swing.JButton BCosec;
    private javax.swing.JButton BCosecInverse;
    private javax.swing.JButton BCosecx;
    private javax.swing.JButton BCosh;
    private javax.swing.JButton BCot;
    private javax.swing.JButton BCotInverse;
    private javax.swing.JButton BCube;
    private javax.swing.JButton BDiv;
    private javax.swing.JButton BDiv1;
    private javax.swing.JButton BDot;
    private javax.swing.JButton BEqual;
    private javax.swing.JButton BExp;
    private javax.swing.JButton BFactorial;
    private javax.swing.JButton BLog;
    private javax.swing.JButton BMul;
    private javax.swing.JRadioButton BOF;
    private javax.swing.JRadioButton BOn;
    private javax.swing.JButton BOpenBracket;
    private javax.swing.JButton BPI;
    private javax.swing.JButton BPercent;
    private javax.swing.JButton BPlusMinus;
    private javax.swing.JButton BReciprocal;
    private javax.swing.JButton BRoot;
    private javax.swing.JButton BSec;
    private javax.swing.JButton BSecInverse;
    private javax.swing.JButton BSin;
    private javax.swing.JButton BSinInverse;
    private javax.swing.JButton BSinh;
    private javax.swing.JButton BSub;
    private javax.swing.JButton BTan;
    private javax.swing.JButton BTanInverse;
    private javax.swing.JButton BTanh;
    private javax.swing.JButton BX;
    private javax.swing.JButton BXPowerY;
    private javax.swing.JButton BZ;
    private javax.swing.JTextField T1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Panel panel1;
    // End of variables declaration                   

    private double doubleIntegrate(double ax, double bx, int nx, double ay, double by, int ny) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private double tripleleIntegrate(double ax, double bx, int nx, double ay, double by, int ny, double az, double bz, int nz) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
